CREATE TABLE student (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255),
                         email VARCHAR(255)
);

CREATE TABLE teacher (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255),
                         department VARCHAR(255)
);

CREATE TABLE course (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR(255) NOT NULL,
                        teacher_id BIGINT NOT NULL,
                        FOREIGN KEY (teacher_id) REFERENCES teacher(id)
);

CREATE TABLE enrollment (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            student_id BIGINT NOT NULL,
                            course_id BIGINT NOT NULL,
                            grade VARCHAR(255),
                            FOREIGN KEY (student_id) REFERENCES student(id),
                            FOREIGN KEY (course_id) REFERENCES course(id)
);